name: Test

on:
   push:
     branches:
       - master
     tags:
       - '*'
   pull_request:
     branches:
       - master

jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Tests
        run: swift test
